server:
  error:
    include-message: always
  port: 8080

spring:
  application:
    name: full-text-search
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        search:
          schema_management:
            strategy: drop-and-create
          backend:
            type: elasticsearch
            hosts: localhost:9200
            schema_management:
              minimal_required_status: yellow
            log:
              json_pretty_printing: true

    hibernate:
      ddl-auto: none
